"""add_contact_emails_table

Revision ID: 6128f86ddead
Revises: 0098d369823b
Create Date: 2026-08-26 13:34:53.872338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6128f86ddead'
down_revision: Union[str, None] = '0098d369823b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_emails_user_id'), 'contact_emails', ['user_id'], unique=False)
    op.drop_constraint(op.f('admin_users_email_key'), 'admin_users', type_='unique')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_constraint(op.f('guests_email_key'), 'guests', type_='unique')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=True)
    op.drop_constraint(op.f('listings_slug_key'), 'listings', type_='unique')
    op.drop_index(op.f('ix_listings_slug'), table_name='listings')
    op.create_index(op.f('ix_listings_slug'), 'listings', ['slug'], unique=True)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_listings_slug'), table_name='listings')
    op.create_index(op.f('ix_listings_slug'), 'listings', ['slug'], unique=False)
    op.create_unique_constraint(op.f('listings_slug_key'), 'listings', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_unique_constraint(op.f('guests_email_key'), 'guests', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('admin_users_email_key'), 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_contact_emails_user_id'), table_name='contact_emails')
    op.drop_table('contact_emails')
    # ### end Alembic commands ###
